// AUTO-GENERATED by scripts/build-manifest.mjs — do not edit by hand.
import type { Problem } from "./types";
export const problems: Problem[] = [
  {
    "type": "coding",
    "meta": {
      "id": "001-two-sum",
      "title": "Two Sum",
      "difficulty": "easy",
      "tags": [
        "array",
        "hash-map"
      ],
      "topics": [
        "arrays"
      ],
      "entry": "twoSum",
      "signature": {
        "params": [
          {
            "array": "int"
          },
          "int"
        ],
        "returns": {
          "array": "int"
        }
      },
      "validator": {
        "kind": "set"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Two Sum\n\nGiven an array of integers `nums` and an integer `target`, return the indices of the two numbers that add up to `target`.\n\nYou may assume each input has exactly one solution, and you may not use the same element twice.\n\n## Example\n\nInput: `nums = [2, 7, 11, 15]`, `target = 9`\nOutput: `[0, 1]` (because `nums[0] + nums[1] == 9`)\n\n## Constraints\n- 2 <= nums.length <= 10^4\n- -10^9 <= nums[i] <= 10^9\n- -10^9 <= target <= 10^9\n",
    "starters": {
      "python": "def twoSum(nums, target):\n    # Return [i, j] such that nums[i] + nums[j] == target.\n    pass\n",
      "javascript": "function twoSum(nums, target) {\n  // Return [i, j] such that nums[i] + nums[j] === target.\n}\n"
    },
    "solutions": {
      "python": "def twoSum(nums, target):\n    seen = {}\n    for i, v in enumerate(nums):\n        if target - v in seen:\n            return [seen[target - v], i]\n        seen[v] = i\n    return []\n",
      "javascript": "function twoSum(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i];\n    if (seen.has(need)) return [seen.get(need), i];\n    seen.set(nums[i], i);\n  }\n  return [];\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            2,
            7,
            11,
            15
          ],
          9
        ],
        "expected": [
          0,
          1
        ]
      },
      {
        "input": [
          [
            3,
            2,
            4
          ],
          6
        ],
        "expected": [
          1,
          2
        ]
      },
      {
        "input": [
          [
            3,
            3
          ],
          6
        ],
        "expected": [
          0,
          1
        ]
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "002-valid-parentheses",
      "title": "Valid Parentheses",
      "difficulty": "easy",
      "tags": [
        "stack",
        "string"
      ],
      "topics": [
        "stack"
      ],
      "entry": "isValid",
      "signature": {
        "params": [
          "string"
        ],
        "returns": "bool"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Valid Parentheses\n\nGiven a string `s` containing only the characters `(`, `)`, `{`, `}`, `[`, and `]`, determine if the string is valid. A string is valid if every open bracket is closed by the same type of bracket, and brackets are closed in the correct order. An empty string is considered valid.\n\n## Example\n\nInput: `s = \"()[]{}\"` → Output: `true`\nInput: `s = \"(]\"` → Output: `false`\nInput: `s = \"([)]\"` → Output: `false`\nInput: `s = \"{[]}\"` → Output: `true`\n\n## Constraints\n- 1 ≤ s.length ≤ 10⁴\n- `s` consists of parentheses characters only: `()[]{}`.\n",
    "starters": {
      "python": "def isValid(s):\n    # Return True if the bracket string is valid, False otherwise.\n    pass\n",
      "javascript": "function isValid(s) {\n  // Return true if the bracket string is valid, false otherwise.\n}\n"
    },
    "solutions": {
      "python": "def isValid(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for c in s:\n        if c in pairs:\n            if not stack or stack.pop() != pairs[c]: return False\n        else:\n            stack.append(c)\n    return not stack\n",
      "javascript": "function isValid(s) {\n  const pairs = { ')': '(', ']': '[', '}': '{' };\n  const stack = [];\n  for (const c of s) {\n    if (c in pairs) {\n      if (!stack.length || stack.pop() !== pairs[c]) return false;\n    } else stack.push(c);\n  }\n  return stack.length === 0;\n}\n"
    },
    "tests": [
      {
        "input": [
          "()[]{}"
        ],
        "expected": true
      },
      {
        "input": [
          "(]"
        ],
        "expected": false
      },
      {
        "input": [
          "([)]"
        ],
        "expected": false
      },
      {
        "input": [
          "{[]}"
        ],
        "expected": true
      },
      {
        "input": [
          ""
        ],
        "expected": true
      }
    ]
  },
  {
    "type": "system_design",
    "meta": {
      "id": "001-design-url-shortener",
      "title": "Design a URL Shortener",
      "estMinutes": 45,
      "tags": [
        "system-design",
        "scalability"
      ]
    },
    "promptMarkdown": "# Design a URL Shortener\n\nDesign a system like bit.ly or TinyURL that shortens long URLs into short ones.\n\n## Requirements\n\n- Given a long URL, generate a short URL (e.g., `https://short.ly/abc123`)\n- Given a short URL, redirect to the original long URL\n- Handle millions of requests per day\n- URLs should not expire unless explicitly set\n\n## Questions to Consider\n\n- How do you generate unique short codes?\n- How do you handle collisions?\n- What is your storage strategy?\n- How do you handle scale?\n"
  }
] as const;
export const codingProblems = problems.filter((p) => p.type === "coding");
export const systemDesignProblems = problems.filter((p) => p.type === "system_design");
