// AUTO-GENERATED by scripts/build-manifest.mjs — do not edit by hand.
import type { Problem } from "./types";
export const problems: Problem[] = [
  {
    "type": "coding",
    "meta": {
      "id": "001-two-sum",
      "title": "Two Sum",
      "difficulty": "easy",
      "tags": [
        "array",
        "hash-map"
      ],
      "topics": [
        "arrays"
      ],
      "entry": "twoSum",
      "signature": {
        "params": [
          {
            "array": "int"
          },
          "int"
        ],
        "returns": {
          "array": "int"
        }
      },
      "validator": {
        "kind": "set"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Two Sum\n\nGiven an array of integers `nums` and an integer `target`, return the indices of the two numbers that add up to `target`.\n\nYou may assume each input has exactly one solution, and you may not use the same element twice.\n\n## Example\n\nInput: `nums = [2, 7, 11, 15]`, `target = 9`\nOutput: `[0, 1]` (because `nums[0] + nums[1] == 9`)\n\n## Constraints\n- 2 <= nums.length <= 10^4\n- -10^9 <= nums[i] <= 10^9\n- -10^9 <= target <= 10^9\n",
    "starters": {
      "python": "def twoSum(nums, target):\n    # Return [i, j] such that nums[i] + nums[j] == target.\n    pass\n",
      "javascript": "function twoSum(nums, target) {\n  // Return [i, j] such that nums[i] + nums[j] === target.\n}\n"
    },
    "solutions": {
      "python": "def twoSum(nums, target):\n    seen = {}\n    for i, v in enumerate(nums):\n        if target - v in seen:\n            return [seen[target - v], i]\n        seen[v] = i\n    return []\n",
      "javascript": "function twoSum(nums, target) {\n  const seen = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const need = target - nums[i];\n    if (seen.has(need)) return [seen.get(need), i];\n    seen.set(nums[i], i);\n  }\n  return [];\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            2,
            7,
            11,
            15
          ],
          9
        ],
        "expected": [
          0,
          1
        ]
      },
      {
        "input": [
          [
            3,
            2,
            4
          ],
          6
        ],
        "expected": [
          1,
          2
        ]
      },
      {
        "input": [
          [
            3,
            3
          ],
          6
        ],
        "expected": [
          0,
          1
        ]
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "002-valid-parentheses",
      "title": "Valid Parentheses",
      "difficulty": "easy",
      "tags": [
        "stack",
        "string"
      ],
      "topics": [
        "stack"
      ],
      "entry": "isValid",
      "signature": {
        "params": [
          "string"
        ],
        "returns": "bool"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Valid Parentheses\n\nGiven a string `s` containing only the characters `(`, `)`, `{`, `}`, `[`, and `]`, determine if the string is valid. A string is valid if every open bracket is closed by the same type of bracket, and brackets are closed in the correct order. An empty string is considered valid.\n\n## Example\n\nInput: `s = \"()[]{}\"` → Output: `true`\nInput: `s = \"(]\"` → Output: `false`\nInput: `s = \"([)]\"` → Output: `false`\nInput: `s = \"{[]}\"` → Output: `true`\n\n## Constraints\n- 1 ≤ s.length ≤ 10⁴\n- `s` consists of parentheses characters only: `()[]{}`.\n",
    "starters": {
      "python": "def isValid(s):\n    # Return True if the bracket string is valid, False otherwise.\n    pass\n",
      "javascript": "function isValid(s) {\n  // Return true if the bracket string is valid, false otherwise.\n}\n"
    },
    "solutions": {
      "python": "def isValid(s):\n    pairs = {')': '(', ']': '[', '}': '{'}\n    stack = []\n    for c in s:\n        if c in pairs:\n            if not stack or stack.pop() != pairs[c]: return False\n        else:\n            stack.append(c)\n    return not stack\n",
      "javascript": "function isValid(s) {\n  const pairs = { ')': '(', ']': '[', '}': '{' };\n  const stack = [];\n  for (const c of s) {\n    if (c in pairs) {\n      if (!stack.length || stack.pop() !== pairs[c]) return false;\n    } else stack.push(c);\n  }\n  return stack.length === 0;\n}\n"
    },
    "tests": [
      {
        "input": [
          "()[]{}"
        ],
        "expected": true
      },
      {
        "input": [
          "(]"
        ],
        "expected": false
      },
      {
        "input": [
          "([)]"
        ],
        "expected": false
      },
      {
        "input": [
          "{[]}"
        ],
        "expected": true
      },
      {
        "input": [
          ""
        ],
        "expected": true
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "003-merge-two-sorted-lists",
      "title": "Merge Two Sorted Lists",
      "difficulty": "easy",
      "tags": [
        "linked-list",
        "recursion"
      ],
      "topics": [
        "linked-list"
      ],
      "entry": "mergeTwoLists",
      "signature": {
        "params": [
          {
            "linked_list": "int"
          },
          {
            "linked_list": "int"
          }
        ],
        "returns": {
          "linked_list": "int"
        }
      },
      "validator": {
        "kind": "linked_list_value_equal"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Merge Two Sorted Lists\n\nYou are given the heads of two sorted linked lists `list1` and `list2`. Merge the two lists into one sorted linked list by splicing together the nodes of the input lists. Return the head of the merged linked list.\n\n## Example\n\nInput: `list1 = [1,2,4]`, `list2 = [1,3,4]`\nOutput: `[1,1,2,3,4,4]`\n\nInput: `list1 = []`, `list2 = []`\nOutput: `[]`\n\nInput: `list1 = []`, `list2 = [0]`\nOutput: `[0]`\n\n## Constraints\n- The number of nodes in each list is in the range `[0, 50]`.\n- -100 ≤ Node.val ≤ 100\n- Both `list1` and `list2` are sorted in non-decreasing order.\n",
    "starters": {
      "python": "def mergeTwoLists(l1, l2):\n    # Merge two sorted linked lists and return the head of the merged list.\n    # ListNode is available in scope (injected by the harness).\n    pass\n",
      "javascript": "function mergeTwoLists(l1, l2) {\n  // Merge two sorted linked lists and return the head of the merged list.\n  // ListNode is available in scope (injected by the harness).\n}\n"
    },
    "solutions": {
      "python": "def mergeTwoLists(l1, l2):\n    dummy = ListNode(0); cur = dummy\n    while l1 and l2:\n        if l1.val <= l2.val: cur.next = l1; l1 = l1.next\n        else: cur.next = l2; l2 = l2.next\n        cur = cur.next\n    cur.next = l1 or l2\n    return dummy.next\n",
      "javascript": "function mergeTwoLists(l1, l2) {\n  const dummy = new ListNode(0); let cur = dummy;\n  while (l1 && l2) {\n    if (l1.val <= l2.val) { cur.next = l1; l1 = l1.next; }\n    else { cur.next = l2; l2 = l2.next; }\n    cur = cur.next;\n  }\n  cur.next = l1 || l2;\n  return dummy.next;\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            1,
            2,
            4
          ],
          [
            1,
            3,
            4
          ]
        ],
        "expected": [
          1,
          1,
          2,
          3,
          4,
          4
        ]
      },
      {
        "input": [
          [],
          []
        ],
        "expected": []
      },
      {
        "input": [
          [],
          [
            0
          ]
        ],
        "expected": [
          0
        ]
      },
      {
        "input": [
          [
            1
          ],
          [
            2
          ]
        ],
        "expected": [
          1,
          2
        ]
      },
      {
        "input": [
          [
            1,
            3,
            5
          ],
          [
            2,
            4,
            6
          ]
        ],
        "expected": [
          1,
          2,
          3,
          4,
          5,
          6
        ]
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "004-best-time-buy-sell",
      "title": "Best Time to Buy and Sell Stock",
      "difficulty": "easy",
      "tags": [
        "array",
        "greedy",
        "sliding-window"
      ],
      "topics": [
        "arrays",
        "greedy"
      ],
      "entry": "maxProfit",
      "signature": {
        "params": [
          {
            "array": "int"
          }
        ],
        "returns": "int"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Best Time to Buy and Sell Stock\n\nYou are given an array `prices` where `prices[i]` is the price of a stock on day `i`. You want to maximize profit by choosing a single day to buy and a later day to sell. Return the maximum profit you can achieve. If no profit is possible, return `0`.\n\n## Example\n\nInput: `prices = [7,1,5,3,6,4]` → Output: `5`\nExplanation: Buy on day 2 (price=1), sell on day 5 (price=6). Profit = 6 - 1 = 5.\n\nInput: `prices = [7,6,4,3,1]` → Output: `0`\nExplanation: Prices only decrease; no transaction gives a profit.\n\n## Constraints\n- 1 ≤ prices.length ≤ 10⁵\n- 0 ≤ prices[i] ≤ 10⁴\n",
    "starters": {
      "python": "def maxProfit(prices):\n    # Return the maximum profit from one buy-then-sell transaction.\n    pass\n",
      "javascript": "function maxProfit(prices) {\n  // Return the maximum profit from one buy-then-sell transaction.\n}\n"
    },
    "solutions": {
      "python": "def maxProfit(prices):\n    best, lo = 0, float('inf')\n    for p in prices:\n        lo = min(lo, p); best = max(best, p - lo)\n    return best\n",
      "javascript": "function maxProfit(prices) {\n  let best = 0, lo = Infinity;\n  for (const p of prices) { lo = Math.min(lo, p); best = Math.max(best, p - lo); }\n  return best;\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            7,
            1,
            5,
            3,
            6,
            4
          ]
        ],
        "expected": 5
      },
      {
        "input": [
          [
            7,
            6,
            4,
            3,
            1
          ]
        ],
        "expected": 0
      },
      {
        "input": [
          [
            1,
            2
          ]
        ],
        "expected": 1
      },
      {
        "input": [
          [
            2,
            1,
            4
          ]
        ],
        "expected": 3
      },
      {
        "input": [
          [
            1
          ]
        ],
        "expected": 0
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "005-valid-anagram",
      "title": "Valid Anagram",
      "difficulty": "easy",
      "tags": [
        "hash-map",
        "string",
        "sorting"
      ],
      "topics": [
        "strings",
        "hash-map"
      ],
      "entry": "isAnagram",
      "signature": {
        "params": [
          "string",
          "string"
        ],
        "returns": "bool"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Valid Anagram\n\nGiven two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise. An anagram is a word formed by rearranging the letters of another word using all the original letters exactly once.\n\n## Example\n\nInput: `s = \"anagram\"`, `t = \"nagaram\"` → Output: `true`\nInput: `s = \"rat\"`, `t = \"car\"` → Output: `false`\n\n## Constraints\n- 1 ≤ s.length, t.length ≤ 5 × 10⁴\n- `s` and `t` consist of lowercase English letters.\n",
    "starters": {
      "python": "def isAnagram(s, t):\n    # Return True if t is an anagram of s, False otherwise.\n    pass\n",
      "javascript": "function isAnagram(s, t) {\n  // Return true if t is an anagram of s, false otherwise.\n}\n"
    },
    "solutions": {
      "python": "def isAnagram(s, t):\n    return sorted(s) == sorted(t)\n",
      "javascript": "function isAnagram(s, t) {\n  if (s.length !== t.length) return false;\n  return [...s].sort().join('') === [...t].sort().join('');\n}\n"
    },
    "tests": [
      {
        "input": [
          "anagram",
          "nagaram"
        ],
        "expected": true
      },
      {
        "input": [
          "rat",
          "car"
        ],
        "expected": false
      },
      {
        "input": [
          "a",
          "a"
        ],
        "expected": true
      },
      {
        "input": [
          "ab",
          "ba"
        ],
        "expected": true
      },
      {
        "input": [
          "abc",
          "ab"
        ],
        "expected": false
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "006-reverse-linked-list",
      "title": "Reverse Linked List",
      "difficulty": "easy",
      "tags": [
        "linked-list",
        "recursion"
      ],
      "topics": [
        "linked-list"
      ],
      "entry": "reverseList",
      "signature": {
        "params": [
          {
            "linked_list": "int"
          }
        ],
        "returns": {
          "linked_list": "int"
        }
      },
      "validator": {
        "kind": "linked_list_value_equal"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Reverse Linked List\n\nGiven the head of a singly linked list, reverse the list and return the reversed list's head.\n\n## Example\n\nInput: `head = [1,2,3,4,5]` → Output: `[5,4,3,2,1]`\nInput: `head = [1,2]` → Output: `[2,1]`\nInput: `head = []` → Output: `[]`\n\n## Constraints\n- The number of nodes in the list is in the range `[0, 5000]`.\n- -5000 ≤ Node.val ≤ 5000\n",
    "starters": {
      "python": "def reverseList(head):\n    # Return the head of the reversed linked list.\n    # ListNode is available in scope (injected by the harness).\n    pass\n",
      "javascript": "function reverseList(head) {\n  // Return the head of the reversed linked list.\n  // ListNode is available in scope (injected by the harness).\n}\n"
    },
    "solutions": {
      "python": "def reverseList(head):\n    prev = None\n    cur = head\n    while cur:\n        nxt = cur.next; cur.next = prev; prev = cur; cur = nxt\n    return prev\n",
      "javascript": "function reverseList(head) {\n  let prev = null, cur = head;\n  while (cur) { const nxt = cur.next; cur.next = prev; prev = cur; cur = nxt; }\n  return prev;\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            1,
            2,
            3,
            4,
            5
          ]
        ],
        "expected": [
          5,
          4,
          3,
          2,
          1
        ]
      },
      {
        "input": [
          [
            1,
            2
          ]
        ],
        "expected": [
          2,
          1
        ]
      },
      {
        "input": [
          []
        ],
        "expected": []
      },
      {
        "input": [
          [
            1
          ]
        ],
        "expected": [
          1
        ]
      },
      {
        "input": [
          [
            3,
            3,
            3
          ]
        ],
        "expected": [
          3,
          3,
          3
        ]
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "007-maximum-subarray",
      "title": "Maximum Subarray",
      "difficulty": "medium",
      "tags": [
        "array",
        "dynamic-programming",
        "divide-and-conquer"
      ],
      "topics": [
        "dynamic-programming",
        "arrays"
      ],
      "entry": "maxSubArray",
      "signature": {
        "params": [
          {
            "array": "int"
          }
        ],
        "returns": "int"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Maximum Subarray\n\nGiven an integer array `nums`, find the subarray with the largest sum and return that sum. A subarray is a contiguous non-empty portion of the array.\n\n## Example\n\nInput: `nums = [-2,1,-3,4,-1,2,1,-5,4]` → Output: `6`\nExplanation: The subarray `[4,-1,2,1]` has the largest sum of 6.\n\nInput: `nums = [1]` → Output: `1`\n\nInput: `nums = [5,4,-1,7,8]` → Output: `23`\n\n## Constraints\n- 1 ≤ nums.length ≤ 10⁵\n- -10⁴ ≤ nums[i] ≤ 10⁴\n",
    "starters": {
      "python": "def maxSubArray(nums):\n    # Return the sum of the contiguous subarray with the largest sum.\n    pass\n",
      "javascript": "function maxSubArray(nums) {\n  // Return the sum of the contiguous subarray with the largest sum.\n}\n"
    },
    "solutions": {
      "python": "def maxSubArray(nums):\n    best = cur = nums[0]\n    for v in nums[1:]:\n        cur = max(v, cur + v); best = max(best, cur)\n    return best\n",
      "javascript": "function maxSubArray(nums) {\n  let best = nums[0], cur = nums[0];\n  for (let i = 1; i < nums.length; i++) { cur = Math.max(nums[i], cur + nums[i]); best = Math.max(best, cur); }\n  return best;\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            -2,
            1,
            -3,
            4,
            -1,
            2,
            1,
            -5,
            4
          ]
        ],
        "expected": 6
      },
      {
        "input": [
          [
            1
          ]
        ],
        "expected": 1
      },
      {
        "input": [
          [
            5,
            4,
            -1,
            7,
            8
          ]
        ],
        "expected": 23
      },
      {
        "input": [
          [
            -1,
            -2,
            -3
          ]
        ],
        "expected": -1
      },
      {
        "input": [
          [
            -2,
            1
          ]
        ],
        "expected": 1
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "008-climbing-stairs",
      "title": "Climbing Stairs",
      "difficulty": "easy",
      "tags": [
        "dynamic-programming",
        "math",
        "memoization"
      ],
      "topics": [
        "dynamic-programming"
      ],
      "entry": "climbStairs",
      "signature": {
        "params": [
          "int"
        ],
        "returns": "int"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Climbing Stairs\n\nYou are climbing a staircase with `n` steps. Each time you can either climb 1 or 2 steps. Return the number of distinct ways you can climb to the top.\n\n## Example\n\nInput: `n = 2` → Output: `2`\nExplanation: Two ways: (1 step + 1 step) or (2 steps).\n\nInput: `n = 3` → Output: `3`\nExplanation: Three ways: (1+1+1), (1+2), (2+1).\n\nInput: `n = 5` → Output: `8`\n\n## Constraints\n- 1 ≤ n ≤ 45\n",
    "starters": {
      "python": "def climbStairs(n):\n    # Return the number of distinct ways to climb n stairs.\n    pass\n",
      "javascript": "function climbStairs(n) {\n  // Return the number of distinct ways to climb n stairs.\n}\n"
    },
    "solutions": {
      "python": "def climbStairs(n):\n    a, b = 1, 1\n    for _ in range(n): a, b = b, a + b\n    return a\n",
      "javascript": "function climbStairs(n) { let a = 1, b = 1; for (let i = 0; i < n; i++) [a, b] = [b, a + b]; return a; }\n"
    },
    "tests": [
      {
        "input": [
          1
        ],
        "expected": 1
      },
      {
        "input": [
          2
        ],
        "expected": 2
      },
      {
        "input": [
          3
        ],
        "expected": 3
      },
      {
        "input": [
          5
        ],
        "expected": 8
      },
      {
        "input": [
          10
        ],
        "expected": 89
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "009-binary-search",
      "title": "Binary Search",
      "difficulty": "easy",
      "tags": [
        "array",
        "binary-search"
      ],
      "topics": [
        "binary-search",
        "arrays"
      ],
      "entry": "search",
      "signature": {
        "params": [
          {
            "array": "int"
          },
          "int"
        ],
        "returns": "int"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Binary Search\n\nGiven a sorted array of integers `nums` in ascending order and a `target` integer, write a function to search for `target` in `nums`. If `target` exists, return its index; otherwise, return `-1`. Your algorithm must run in O(log n) time.\n\n## Example\n\nInput: `nums = [-1,0,3,5,9,12]`, `target = 9` → Output: `4`\nExplanation: 9 exists in `nums` and its index is 4.\n\nInput: `nums = [-1,0,3,5,9,12]`, `target = 2` → Output: `-1`\nExplanation: 2 does not exist in `nums`.\n\n## Constraints\n- 1 ≤ nums.length ≤ 10⁴\n- -10⁴ ≤ nums[i], target ≤ 10⁴\n- All integers in `nums` are unique.\n- `nums` is sorted in ascending order.\n",
    "starters": {
      "python": "def search(nums, target):\n    # Return the index of target in nums, or -1 if not found.\n    pass\n",
      "javascript": "function search(nums, target) {\n  // Return the index of target in nums, or -1 if not found.\n}\n"
    },
    "solutions": {
      "python": "def search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target: return mid\n        if nums[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1\n",
      "javascript": "function search(nums, target) {\n  let lo = 0, hi = nums.length - 1;\n  while (lo <= hi) {\n    const mid = (lo + hi) >> 1;\n    if (nums[mid] === target) return mid;\n    if (nums[mid] < target) lo = mid + 1; else hi = mid - 1;\n  }\n  return -1;\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            -1,
            0,
            3,
            5,
            9,
            12
          ],
          9
        ],
        "expected": 4
      },
      {
        "input": [
          [
            -1,
            0,
            3,
            5,
            9,
            12
          ],
          2
        ],
        "expected": -1
      },
      {
        "input": [
          [
            1
          ],
          1
        ],
        "expected": 0
      },
      {
        "input": [
          [
            1,
            3,
            5,
            7,
            9
          ],
          7
        ],
        "expected": 3
      },
      {
        "input": [
          [
            2,
            5,
            8,
            12,
            16
          ],
          100
        ],
        "expected": -1
      }
    ]
  },
  {
    "type": "coding",
    "meta": {
      "id": "010-linked-list-cycle",
      "title": "Linked List Cycle",
      "difficulty": "easy",
      "tags": [
        "linked-list",
        "two-pointers",
        "hash-table"
      ],
      "topics": [
        "linked-list",
        "two-pointers"
      ],
      "entry": "hasCycle",
      "signature": {
        "params": [
          {
            "linked_list": "int"
          }
        ],
        "returns": "bool"
      },
      "validator": {
        "kind": "exact"
      },
      "timeLimitMs": 5000
    },
    "statementMarkdown": "# Linked List Cycle\n\nGiven the head of a linked list, determine if the linked list contains a cycle. A cycle exists if some node in the list can be reached again by continuously following the `next` pointer. Return `true` if there is a cycle, or `false` otherwise.\n\nThe classic approach is Floyd's cycle-detection (two-pointer / \"tortoise and hare\") which uses O(1) extra space.\n\n## Example\n\nInput: `head = [3,2,0,-4]` (cycle: tail connects back to index 1) → Output: `true`\nInput: `head = [1,2]` (cycle: tail connects back to index 0) → Output: `true`\nInput: `head = [1]` (no cycle) → Output: `false`\n\n## Constraints\n- The number of nodes is in the range `[0, 10⁴]`.\n- -10⁵ ≤ Node.val ≤ 10⁵\n\n## v1 Limitation\n\nThe v1 test schema cannot express cyclic input; all test cases use acyclic lists where the expected answer is always `false`. v1.1 may extend the schema with a `cycleIndex` per test case to support cycle inputs.\n",
    "starters": {
      "python": "def hasCycle(head):\n    # Return True if the linked list contains a cycle, False otherwise.\n    # ListNode is available in scope (injected by the harness).\n    pass\n",
      "javascript": "function hasCycle(head) {\n  // Return true if the linked list contains a cycle, false otherwise.\n  // ListNode is available in scope (injected by the harness).\n}\n"
    },
    "solutions": {
      "python": "def hasCycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow = slow.next; fast = fast.next.next\n        if slow is fast: return True\n    return False\n",
      "javascript": "function hasCycle(head) {\n  let slow = head, fast = head;\n  while (fast && fast.next) { slow = slow.next; fast = fast.next.next; if (slow === fast) return true; }\n  return false;\n}\n"
    },
    "tests": [
      {
        "input": [
          [
            3,
            2,
            0,
            -4
          ]
        ],
        "expected": false
      },
      {
        "input": [
          [
            1,
            2
          ]
        ],
        "expected": false
      },
      {
        "input": [
          [
            1
          ]
        ],
        "expected": false
      },
      {
        "input": [
          []
        ],
        "expected": false
      },
      {
        "input": [
          [
            1,
            2,
            3,
            4,
            5
          ]
        ],
        "expected": false
      }
    ]
  },
  {
    "type": "system_design",
    "meta": {
      "id": "001-design-url-shortener",
      "title": "Design a URL Shortener",
      "estMinutes": 45,
      "tags": [
        "system-design",
        "scalability"
      ]
    },
    "promptMarkdown": "# Design a URL Shortener\n\nDesign a system like bit.ly or TinyURL that shortens long URLs into short ones.\n\n## Requirements\n\n- Given a long URL, generate a short URL (e.g., `https://short.ly/abc123`)\n- Given a short URL, redirect to the original long URL\n- Handle millions of requests per day\n- URLs should not expire unless explicitly set\n\n## Questions to Consider\n\n- How do you generate unique short codes?\n- How do you handle collisions?\n- What is your storage strategy?\n- How do you handle scale?\n"
  }
] as const;
export const codingProblems = problems.filter((p) => p.type === "coding");
export const systemDesignProblems = problems.filter((p) => p.type === "system_design");
